-- ======================
-- Banco de Dados EMPRESA
-- ======================




DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE Funcionario (
  CODFUNC   INT,
  NOME      VARCHAR(40) NOT NULL,
  DEPTO     CHAR(2),
  FUNCAO    VARCHAR(20),
  SALARIO   DECIMAL(6, 2),
  ADMISSAO  DATE,
  FILHOS    SMALLINT,
  PRIMARY KEY (CODFUNC)
);

INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (1,'CARLOS MACEDO CERRI', 3, 'VENDEDOR', 1530.00, '2020-05-25', NULL);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (2, 'HENRIQUE SOUZA MARCOS', 2, 'GERENTE', 3985.75, '2019-07-01', 2);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (3, 'ADRIANA ARAUJO DA SILVA', 3, 'SECRETARIA', 1200.50, '2020-07-10', 1);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (4, 'SOLANGE APARECIDA SOUZA', 5, 'SUPERVISOR', 1599.51, '2016-12-08', 3);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (5, 'MARCELO AMORIM PACHECO', 3, 'ANALISTA', 2850.11, '2015-06-06', NULL);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (6,'CELIA ASSIS DO AMARAL', 2, 'SECRETARIA', 1200.50, '2019-01-10', 1);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (7, 'WILSON CAMPOS MACEDO', 3, 'PROGRAMADOR', 2050.00, '2022-11-07', NULL);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (8, 'AUGUSTO AGUIAR SOUZA', 3, 'PROGRAMADOR', 2050.00, '2020-05-26', NULL);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (9, 'JESSICA ALVES TOLEDO', 2, 'SUPERVISOR', 2100.00, '2016-07-05', 4);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (10, 'VITORIA CRUZ ALMEIDA', 2,'ANALISTA', 2500.00, '2016-05-23', 1);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (11, 'MARCIO CANUTO DOS SANTOS', 2, 'PROGRAMADOR', 1800.00, '2018-07-29', NULL);
INSERT INTO Funcionario (CODFUNC, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS) VALUES (12, 'CRISTINA CACHOEIRA BUZZI', 5, 'SUPERVISOR', 1950.00, '2021-07-14', 2);


-- SHOW TABLES;
-- DESC Funcionario;
